### ISSUE TITLE
Pytorch version issue in example Part4_NeuralFX/037a_train_lstm

### ISSUE THREAD

**Issue by lassski** [yeeking/ai-enhanced-audio-book#4]
First of all, thank you for the much-needed and well-thought-out book!

The issue: running train.py does not work with the latest PyTorch version (2.6.0) when using CUDA. It works with the CPU, but when using CUDA, it gives the following error: "RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input." Downgrading PyTorch to version 2.1.0 resolves this issue. It might work with more recent versions, but the error occurs with versions 2.6.0 and 2.5.1 at least.

**Comment by yeeking** [comment]
Thanks @lassski  for reporting this.

I have checked it out on my cuda machine here.

Yes - looks like pytorch needs to be <= 2.2. You also need numpy<2. 

To make it run here, I did this:

```
pip install "torch==2.2" "numpy<2"
````
This is not ideal so I am working on a proper fix to get it to run with torch 2.6. 

Will post here once I have a fix. 

Thanks

**Comment by yeeking** [comment]
Hello again @lassski 

I have now fixed the training script so it runs in torch 2.6. 

The error was actually  that this function:
```
def run_file_through_model(model, infile, outfile, samplerate=44100, device='cpu'):
```
was sending a large tensor into the network which CUDNN in 2.60 did not like. So I changed it to send the audio file in segments instead of whole and now it works. 

Thanks for reporting.
